### Setup

In [1]:
# setup
import os
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path("../..").resolve()
load_dotenv(ROOT / ".env")
DB_PATH = ROOT / os.getenv("DUCKDB_PATH", "data/duckDB/primer_impacto.duckdb")
MARTS = "marts"

In [2]:
# functions
%run -i utils/inspect_functions.ipynb

### Tables

In [3]:
show_tables(MARTS)

                         name        type  columns   rows
0         bridge_route_worker  BASE TABLE        5    457
1                dim_campaign  BASE TABLE       13     72
2                  dim_client  BASE TABLE        4     14
3                     dim_pos  BASE TABLE        7    250
4                 dim_project  BASE TABLE        4     28
5                dim_question  BASE TABLE        7    648
6                   dim_route  BASE TABLE        8    242
7                  dim_worker  BASE TABLE        5     45
8               fct_responses  BASE TABLE        9  10192
9                  fct_visits  BASE TABLE       10   1747
10  mart_campaign_performance  BASE TABLE       22    277
11          mart_pos_coverage  BASE TABLE        5   1456
12     mart_route_performance  BASE TABLE       16    241
13       mart_visit_responses  BASE TABLE       21  10192
14    mart_worker_performance  BASE TABLE        8     34

### Keys

In [4]:
find_keys(profile_columns(MARTS))

                 table_name            column_name     type   rows
0       bridge_route_worker      route_employee_id  INTEGER    457
1              dim_campaign            campaign_id  INTEGER     72
2                dim_client              client_id  INTEGER     14
3                   dim_pos  intervention_point_id  INTEGER    250
4               dim_project             project_id  INTEGER     28
5              dim_question            question_id  INTEGER    648
6                 dim_route               route_id  INTEGER    242
7                dim_worker            employee_id  INTEGER     45
8             fct_responses              answer_id  INTEGER  10192
9                fct_visits               visit_id  INTEGER   1747
10   mart_route_performance               route_id  INTEGER    241
11     mart_visit_responses              answer_id  INTEGER  10192
12  mart_worker_performance            employee_id  INTEGER     34

### dim_client

In [5]:
show_table(MARTS, "dim_client")

   client_id                  client_name country        sector
0          1  Laboratorios Valtera España   SPAIN         Farma
1          4           Biofarma España SL   SPAIN  Gran Consumo
2          6               Farmanat Group   SPAIN         Farma
3          8            Novapharma España   SPAIN         Farma
4         10           Clinipharma España   SPAIN         Farma

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_client,client_id,INTEGER,14,0,14,1,14,0.0
1,dim_client,client_name,VARCHAR,14,0,14,Aquilea Consumer Health,Vitahealth España,0.0
2,dim_client,country,VARCHAR,14,0,1,SPAIN,SPAIN,0.0
3,dim_client,sector,VARCHAR,14,0,3,Farma,Parafarmacia,0.0

Empty DataFrame
Columns: [model, column, test, to]
Index: []

### dim_project

In [6]:
show_table(MARTS, "dim_project")

   project_id              project_name   project_type  client_id
0           1  Proyecto Mantenimiento 1  Mantenimiento          1
1           2      Proyecto Formación 2      Formación          2
2           3    Proyecto Visibilidad 3    Visibilidad          2
3           4    Proyecto Visibilidad 4    Visibilidad          2
4           5      Proyecto Auditoria 5      Auditoria          3

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_project,project_id,INTEGER,28,0,28,1,28,0.0
1,dim_project,project_name,VARCHAR,28,0,28,Proyecto Auditoria 15,Proyecto Visibilidad 8,0.0
2,dim_project,project_type,VARCHAR,28,0,5,Auditoria,Visibilidad,0.0
3,dim_project,client_id,INTEGER,28,0,14,1,14,0.0

Empty DataFrame
Columns: [model, column, test, to]
Index: []

### dim_campaign

In [7]:
show_table(MARTS, "dim_campaign")

,client_id,client_name,sector,project_id,project_name,project_type,campaign_id,campaign_name,campaign_start_date,campaign_end_date,visit_duration_minutes,total_visits_planned,total_pos_planned
0,1,Laboratorios Valtera España,Farma,1,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2025-10-20,2026-03-12,45,141,52
1,1,Laboratorios Valtera España,Farma,1,Proyecto Mantenimiento 1,Mantenimiento,2,Campaña Jan 2026 – Proyecto Mantenimiento 1,2026-01-11,2026-02-25,60,376,197
2,2,Pharmakon Consumer Health,Farma,2,Proyecto Formación 2,Formación,3,Campaña Nov 2025 – Proyecto Formación 2,2025-11-18,2026-03-03,45,45,159
3,2,Pharmakon Consumer Health,Farma,2,Proyecto Formación 2,Formación,4,Campaña Oct 2025 – Proyecto Formación 2,2025-10-15,2026-03-24,60,311,73
4,2,Pharmakon Consumer Health,Farma,3,Proyecto Visibilidad 3,Visibilidad,5,Campaña Jan 2026 – Proyecto Visibilidad 3,2026-01-16,2026-07-14,30,222,43

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_campaign,client_id,INTEGER,72,0,14,1,14,0.0
1,dim_campaign,client_name,VARCHAR,72,0,14,Aquilea Consumer Health,Vitahealth España,0.0
2,dim_campaign,sector,VARCHAR,72,0,3,Farma,Parafarmacia,0.0
3,dim_campaign,project_id,INTEGER,72,0,28,1,28,0.0
4,dim_campaign,project_name,VARCHAR,72,0,28,Proyecto Auditoria 15,Proyecto Visibilidad 8,0.0
5,dim_campaign,project_type,VARCHAR,72,0,5,Auditoria,Visibilidad,0.0
6,dim_campaign,campaign_id,INTEGER,72,0,72,1,72,0.0
7,dim_campaign,campaign_name,VARCHAR,72,0,59,Campaña Dec 2025 – Proyecto Auditoria 15,Campaña Oct 2025 – Proyecto Visibilidad 4,0.0
8,dim_campaign,campaign_start_date,DATE,72,0,59,2025-10-03,2026-02-28,0.0
9,dim_campaign,campaign_end_date,DATE,72,0,62,2025-09-29,2026-07-25,0.0
10,dim_campaign,visit_duration_minutes,INTEGER,72,13,5,15,60,18.1
11,dim_campaign,total_visits_planned,INTEGER,72,0,68,20,400,0.0
12,dim_campaign,total_pos_planned,INTEGER,72,0,59,17,250,0.0

           model        column               test to
7   dim_campaign   campaign_id           not_null
8   dim_campaign   campaign_id             unique
9   dim_campaign     client_id           not_null
10  dim_campaign    project_id           not_null
11  dim_campaign  project_type    accepted_values
12  dim_campaign  project_type           not_null
13  dim_campaign           NaN  row_count_matches

### dim_pos

In [8]:
show_table(MARTS, "dim_pos")

,intervention_point_id,intervention_point_name,intervention_point_province,intervention_point_locality,intervention_point_latitude,intervention_point_longitude,intervention_point_is_active
0,1,CONDISLIFE EL TEU SÚPER 1,GUADALAJARA,Localidad 50,41.774104,-5.411961,True
1,2,CONDIS EL TEU SÚPER 2,LAS PALMAS,Localidad 32,37.338316,-7.198834,False
2,3,CEPSA 3,ASTURIAS,Localidad 37,39.344115,-6.713749,True
3,4,CEPSA 4,EVORA,Localidad 46,39.270433,0.871244,<NA>
4,5,DIA % MARKET 5,CACERES,Localidad 44,40.742044,-7.411996,True

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_pos,intervention_point_id,INTEGER,250,0,250,1,250,0.0
1,dim_pos,intervention_point_name,VARCHAR,250,6,244,AROMAS 127,SUPERMERCADOS MIRANDA 89,2.4
2,dim_pos,intervention_point_province,VARCHAR,250,14,46,A CORUNA,ZARAGOZA,5.6
3,dim_pos,intervention_point_locality,VARCHAR,250,26,50,Localidad 1,Localidad 9,10.4
4,dim_pos,intervention_point_latitude,DOUBLE,250,15,235,36.048152,43.371965,6.0
5,dim_pos,intervention_point_longitude,DOUBLE,250,7,243,-8.474971,3.395517,2.8
6,dim_pos,intervention_point_is_active,BOOLEAN,250,10,2,false,true,4.0

      model                       column                 test to
14  dim_pos        intervention_point_id             not_null
15  dim_pos        intervention_point_id               unique
16  dim_pos  intervention_point_province  no_inverted_article
17  dim_pos  intervention_point_province   text_is_normalized
18  dim_pos                          NaN    row_count_matches

### dim_route

In [9]:
show_table(MARTS, "dim_route")

,route_id,route_code,campaign_id,route_name,route_start_date,route_end_date,route_status,delegation_code
0,1,NaN,1,Ruta 1,2026-01-01,2026-03-01,UNKNOWN,DLG15
1,2,RUT00002,1,Ruta 2,2026-01-18,2026-04-10,UNKNOWN,DLG04
2,3,RUT00003,1,Ruta 3,2026-03-31,2026-05-13,ALTA,DLG07
3,4,RUT00004,2,Ruta 4,2026-01-13,2026-02-19,ALTA,DLG06
4,5,RUT00005,2,Ruta 5,2026-01-11,2026-02-23,BAJA,DLG12

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_route,route_id,INTEGER,242,0,242,-1,241,0.0
1,dim_route,route_code,VARCHAR,242,13,229,RUT00002,RUT00241,5.4
2,dim_route,campaign_id,INTEGER,242,1,72,1,72,0.4
3,dim_route,route_name,VARCHAR,242,8,234,No route,Ruta 99,3.3
4,dim_route,route_start_date,DATE,242,1,134,2025-10-09,2026-04-30,0.4
5,dim_route,route_end_date,DATE,242,1,168,2025-10-27,2026-10-17,0.4
6,dim_route,route_status,VARCHAR,242,0,4,ALTA,UNKNOWN,0.0
7,dim_route,delegation_code,VARCHAR,242,28,15,DLG01,DLG15,11.6

,model,column,test,to
23,dim_route,campaign_id,relationships,ref('dim_campaign').campaign_id
24,dim_route,route_id,not_null,
25,dim_route,route_id,unique,
26,dim_route,route_status,accepted_values,
27,dim_route,NaN,row_count_matches,

### dim_worker

In [10]:
show_table(MARTS, "dim_worker")

,employee_id,employee_first_name,employee_active_status,employee_address_province,employee_contract_type
0,6,Carlos,False,TARRAGONA,NaN
1,8,Carlos,True,CASTELLON,NaN
2,10,Ana,False,ASTURIAS,TEMP
3,19,Isabel,True,CANILLO,NaN
4,22,José,True,PORTALEGRE,NaN

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_worker,employee_id,INTEGER,45,0,45,1,45,0.0
1,dim_worker,employee_first_name,VARCHAR,45,0,14,Ana,Sara,0.0
2,dim_worker,employee_active_status,BOOLEAN,45,3,2,false,true,6.7
3,dim_worker,employee_address_province,VARCHAR,45,1,29,A CORUNA,ZAMORA,2.2
4,dim_worker,employee_contract_type,VARCHAR,45,13,3,INDEF,TEMP,28.9

         model                     column                 test to
28  dim_worker  employee_address_province  no_inverted_article
29  dim_worker  employee_address_province   text_is_normalized
30  dim_worker                employee_id             not_null
31  dim_worker                employee_id               unique
32  dim_worker                        NaN    row_count_matches

### dim_question

In [11]:
show_table(MARTS, "dim_question")

,question_id,campaign_id,question_name,question_type,question_category,question_order,question_is_highlighted
0,1,1,En caso de hacer una mejora en Strepsils/Stref...,M,2. Visibilidad,1,False
1,2,1,"En caso de hacer una mejora en Nurofen, indícalo",M,2. Visibilidad,2,False
2,3,1,Indica el nº de facings de Reflex Spray,S,2. Visibilidad,3,False
3,4,1,¿Se ha realizado toda la instalación del vinil...,S,2.Visita,4,False
4,5,1,Que producto en concreto?,T,1. Visita,5,False

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_question,question_id,INTEGER,648,0,648,1,648,0.0
1,dim_question,campaign_id,INTEGER,648,0,72,1,72,0.0
2,dim_question,question_name,VARCHAR,648,18,26,CONTACTO VISITA,¿Se ha realizado toda la instalación del vinil...,2.8
3,dim_question,question_type,VARCHAR,648,28,4,M,T,4.3
4,dim_question,question_category,VARCHAR,648,54,4,1. Visita,2.Visita,8.3
5,dim_question,question_order,INTEGER,648,23,14,1,14,3.5
6,dim_question,question_is_highlighted,BOOLEAN,648,0,2,false,true,0.0

           model       column               test to
19  dim_question  campaign_id           not_null
20  dim_question  question_id           not_null
21  dim_question  question_id             unique
22  dim_question          NaN  row_count_matches

### bridge_route_worker

In [12]:
show_table(MARTS, "bridge_route_worker")

   route_employee_id  route_id  employee_id  main_employee  ip_percentage
0                  1         1           32           True          100.0
1                  2         1           44          False           19.0
2                  3         2           19           True          100.0
3                  4         2           35          False           44.8
4                  6         3            9          False           19.4

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,bridge_route_worker,route_employee_id,INTEGER,457,0,457,1,482,0.0
1,bridge_route_worker,route_id,INTEGER,457,0,240,1,241,0.0
2,bridge_route_worker,employee_id,INTEGER,457,0,34,1,45,0.0
3,bridge_route_worker,main_employee,BOOLEAN,457,0,2,false,true,0.0
4,bridge_route_worker,ip_percentage,DOUBLE,457,14,164,10.2,100.0,3.1

,model,column,test,to
0,bridge_route_worker,employee_id,not_null,
1,bridge_route_worker,employee_id,relationships,ref('dim_worker').employee_id
2,bridge_route_worker,route_employee_id,not_null,
3,bridge_route_worker,route_employee_id,unique,
4,bridge_route_worker,route_id,not_null,
5,bridge_route_worker,route_id,relationships,ref('dim_route').route_id
6,bridge_route_worker,NaN,row_count_matches,

### fct_visits

In [13]:
show_table(MARTS, "fct_visits")

,visit_id,campaign_id,intervention_point_id,route_id,employee_id,visit_date,visit_time,visit_status,visit_type,is_client_billable
0,28,2,157,5,36,2026-01-31,19:45:00,INCID,V,True
1,49,2,138,6,3,2026-01-28,13:45:00,NOVIS,C,True
2,50,2,84,8,34,2026-01-26,08:15:00,INFO,C,True
3,86,4,206,15,15,2026-02-16,09:15:00,NOVIS,V,False
4,87,4,138,15,15,2026-03-02,19:15:00,INCID,NaN,True

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,fct_visits,visit_id,INTEGER,1747,0,1747,1,1747,0.0
1,fct_visits,campaign_id,INTEGER,1747,0,64,1,72,0.0
2,fct_visits,intervention_point_id,INTEGER,1747,0,248,1,250,0.0
3,fct_visits,route_id,INTEGER,1747,0,201,-1,241,0.0
4,fct_visits,employee_id,INTEGER,1747,252,34,1,45,14.4
5,fct_visits,visit_date,DATE,1747,37,139,2026-01-01,2026-05-19,2.1
6,fct_visits,visit_time,TIME,1747,179,48,08:00:00,19:45:00,10.2
7,fct_visits,visit_status,VARCHAR,1747,0,5,INCID,UNKNOWN,0.0
8,fct_visits,visit_type,VARCHAR,1747,664,3,C,V,38.0
9,fct_visits,is_client_billable,BOOLEAN,1747,105,2,false,true,6.0

,model,column,test,to
44,fct_visits,campaign_id,not_null,
45,fct_visits,campaign_id,relationships,ref('dim_campaign').campaign_id
46,fct_visits,employee_id,relationships,ref('dim_worker').employee_id
47,fct_visits,intervention_point_id,not_null,
48,fct_visits,intervention_point_id,relationships,ref('dim_pos').intervention_point_id
49,fct_visits,route_id,not_null,
50,fct_visits,route_id,relationships,ref('dim_route').route_id
51,fct_visits,visit_id,not_null,
52,fct_visits,visit_id,unique,
53,fct_visits,visit_status,accepted_values,
54,fct_visits,visit_status,not_null,
55,fct_visits,NaN,row_count_matches,

### fct_responses

In [14]:
show_table(MARTS, "fct_responses")

,answer_id,visit_id,question_id,campaign_id,intervention_point_id,visit_date,visit_status,question_type,answer
0,1,1,4,1,56,2026-01-02,INFO,S,"No, rechazan la instalación"
1,2,1,12,1,56,2026-01-02,INFO,T,Sin comentarios
2,3,1,8,1,56,2026-01-02,INFO,S,"0, No tienen stock"
3,4,1,6,1,56,2026-01-02,INFO,S,"0, No esta expuesto"
4,5,1,5,1,56,2026-01-02,INFO,T,Auxiliar de farmacia

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,fct_responses,answer_id,INTEGER,10192,0,10192,1,10192,0.0
1,fct_responses,visit_id,INTEGER,10192,0,1747,1,1747,0.0
2,fct_responses,question_id,INTEGER,10192,288,564,1,648,2.8
3,fct_responses,campaign_id,INTEGER,10192,0,64,1,72,0.0
4,fct_responses,intervention_point_id,INTEGER,10192,0,248,1,250,0.0
5,fct_responses,visit_date,DATE,10192,201,139,2026-01-01,2026-05-19,2.0
6,fct_responses,visit_status,VARCHAR,10192,0,5,INCID,UNKNOWN,0.0
7,fct_responses,question_type,VARCHAR,10192,509,4,M,T,5.0
8,fct_responses,answer,VARCHAR,10192,1025,67,"0, No esta expuesto",Visita OK,10.1

,model,column,test,to
33,fct_responses,answer_id,not_null,
34,fct_responses,answer_id,unique,
35,fct_responses,campaign_id,not_null,
36,fct_responses,campaign_id,relationships,ref('dim_campaign').campaign_id
37,fct_responses,intervention_point_id,not_null,
38,fct_responses,intervention_point_id,relationships,ref('dim_pos').intervention_point_id
39,fct_responses,question_id,relationships,ref('dim_question').question_id
40,fct_responses,visit_id,not_null,
41,fct_responses,visit_status,accepted_values,
42,fct_responses,visit_status,not_null,
43,fct_responses,NaN,row_count_matches,

### mart_campaign_performance

In [15]:
show_table(MARTS, "mart_campaign_performance")

,client_name,project_name,project_type,campaign_id,campaign_name,campaign_phase,visit_month,is_campaign_total,visits_recorded,visits_done,...,visits_info,visits_not_done,visits_unknown,pct_not_done,pos_covered,visits_billable,visits_with_billing_flag,pct_billable,field_hours,reference_date
0,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,2,Campaña Jan 2026 – Proyecto Mantenimiento 1,Closed,2026-01-01,False,25,22,...,3,3,0,0.120,22,13,17,0.765,22.000000,2026-05-19
1,Farmanat Group,Proyecto Mantenimiento 10,Mantenimiento,22,Campaña Nov 2025 – Proyecto Mantenimiento 10,Closed,2026-01-01,False,4,3,...,1,1,0,0.250,3,2,3,0.667,NaN,2026-05-19
2,Clinipharma España,Proyecto Mantenimiento 19,Mantenimiento,47,Campaña Jan 2026 – Proyecto Mantenimiento 19,Closed,2026-05-01,False,3,3,...,1,0,0,0.000,3,3,3,1.000,NaN,2026-05-19
3,Salutem Laboratorios,Proyecto Formación 20,Formación,49,Campaña Oct 2025 – Proyecto Formación 20,Closed,2026-01-01,False,40,33,...,7,1,6,0.025,31,22,32,0.688,11.000000,2026-05-19
4,Eurofarma Iberia,Proyecto Visibilidad 21,Visibilidad,53,Campaña Dec 2025 – Proyecto Visibilidad 21,Active,2026-01-01,False,5,5,...,0,0,0,0.000,5,3,4,0.750,1.666667,2026-05-19

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,mart_campaign_performance,client_name,VARCHAR,277,0,14,Aquilea Consumer Health,Vitahealth España,0.0
1,mart_campaign_performance,project_name,VARCHAR,277,0,28,Proyecto Auditoria 15,Proyecto Visibilidad 8,0.0
2,mart_campaign_performance,project_type,VARCHAR,277,0,5,Auditoria,Visibilidad,0.0
3,mart_campaign_performance,campaign_id,INTEGER,277,0,72,1,72,0.0
4,mart_campaign_performance,campaign_name,VARCHAR,277,0,59,Campaña Dec 2025 – Proyecto Auditoria 15,Campaña Oct 2025 – Proyecto Visibilidad 4,0.0
5,mart_campaign_performance,campaign_phase,VARCHAR,277,0,2,Active,Closed,0.0
6,mart_campaign_performance,visit_month,DATE,277,72,5,2026-01-01,2026-05-01,26.0
7,mart_campaign_performance,is_campaign_total,BOOLEAN,277,0,2,false,true,0.0
8,mart_campaign_performance,visits_recorded,BIGINT,277,0,44,0,48,0.0
9,mart_campaign_performance,visits_done,BIGINT,277,0,39,0,45,0.0
10,mart_campaign_performance,visits_ok,BIGINT,277,0,6,0,5,0.0
11,mart_campaign_performance,visits_incident,BIGINT,277,0,32,0,34,0.0
12,mart_campaign_performance,visits_info,BIGINT,277,0,13,0,12,0.0
13,mart_campaign_performance,visits_not_done,BIGINT,277,0,6,0,6,0.0
14,mart_campaign_performance,visits_unknown,BIGINT,277,0,7,0,6,0.0
15,mart_campaign_performance,pct_not_done,DOUBLE,277,8,60,0.0,1.0,2.9
16,mart_campaign_performance,pos_covered,BIGINT,277,0,39,0,42,0.0
17,mart_campaign_performance,visits_billable,BIGINT,277,0,28,0,29,0.0
18,mart_campaign_performance,visits_with_billing_flag,BIGINT,277,0,40,0,40,0.0
19,mart_campaign_performance,pct_billable,DOUBLE,277,15,68,0.0,1.0,5.4
20,mart_campaign_performance,field_hours,DOUBLE,277,50,75,0.0,45.0,18.1
21,mart_campaign_performance,reference_date,DATE,277,0,1,2026-05-19,2026-05-19,0.0

,model,column,test,to
56,mart_campaign_performance,campaign_id,not_null,
57,mart_campaign_performance,campaign_id,relationships,ref('dim_campaign').campaign_id
58,mart_campaign_performance,campaign_phase,accepted_values,
59,mart_campaign_performance,NaN,grain_is_unique,

### mart_pos_coverage

In [16]:
show_table(MARTS, "mart_pos_coverage")

,client_name,project_type,campaign_id,intervention_point_id,visits_done
0,Medicolab Iberia,Auditoria,7,121,1
1,Dermocare Iberia,Sell-In,31,116,1
2,Clinipharma España,Formación,45,237,2
3,Eurofarma Iberia,Visibilidad,53,12,1
4,Dermocare Iberia,Auditoria,32,5,1

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,mart_pos_coverage,client_name,VARCHAR,1456,0,13,Aquilea Consumer Health,Vitahealth España,0.0
1,mart_pos_coverage,project_type,VARCHAR,1456,0,5,Auditoria,Visibilidad,0.0
2,mart_pos_coverage,campaign_id,INTEGER,1456,0,64,1,72,0.0
3,mart_pos_coverage,intervention_point_id,INTEGER,1456,0,248,1,250,0.0
4,mart_pos_coverage,visits_done,BIGINT,1456,0,3,1,3,0.0

,model,column,test,to
60,mart_pos_coverage,campaign_id,not_null,
61,mart_pos_coverage,campaign_id,relationships,ref('dim_campaign').campaign_id
62,mart_pos_coverage,intervention_point_id,not_null,
63,mart_pos_coverage,intervention_point_id,relationships,ref('dim_pos').intervention_point_id
64,mart_pos_coverage,NaN,grain_is_unique,

### mart_route_performance

In [17]:
show_table(MARTS, "mart_route_performance")

,route_id,route_code,route_name,client_name,project_name,project_type,campaign_id,campaign_name,route_start_date,route_end_date,route_status,total_visits,reference_date,is_closed,is_closed_without_visits,days_since_closed
0,1,NaN,Ruta 1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-01,2026-03-01,UNKNOWN,6,2026-05-19,True,False,<NA>
1,2,RUT00002,Ruta 2,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-18,2026-04-10,UNKNOWN,2,2026-05-19,True,False,<NA>
2,3,RUT00003,Ruta 3,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-03-31,2026-05-13,ALTA,8,2026-05-19,True,False,<NA>
3,4,RUT00004,Ruta 4,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,2,Campaña Jan 2026 – Proyecto Mantenimiento 1,2026-01-13,2026-02-19,ALTA,8,2026-05-19,True,False,<NA>
4,5,RUT00005,Ruta 5,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,2,Campaña Jan 2026 – Proyecto Mantenimiento 1,2026-01-11,2026-02-23,BAJA,6,2026-05-19,True,False,<NA>

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,mart_route_performance,route_id,INTEGER,241,0,241,1,241,0.0
1,mart_route_performance,route_code,VARCHAR,241,12,229,RUT00002,RUT00241,5.0
2,mart_route_performance,route_name,VARCHAR,241,8,233,Ruta 1,Ruta 99,3.3
3,mart_route_performance,client_name,VARCHAR,241,0,14,Aquilea Consumer Health,Vitahealth España,0.0
4,mart_route_performance,project_name,VARCHAR,241,0,28,Proyecto Auditoria 15,Proyecto Visibilidad 8,0.0
5,mart_route_performance,project_type,VARCHAR,241,0,5,Auditoria,Visibilidad,0.0
6,mart_route_performance,campaign_id,INTEGER,241,0,72,1,72,0.0
7,mart_route_performance,campaign_name,VARCHAR,241,0,59,Campaña Dec 2025 – Proyecto Auditoria 15,Campaña Oct 2025 – Proyecto Visibilidad 4,0.0
8,mart_route_performance,route_start_date,DATE,241,0,134,2025-10-09,2026-04-30,0.0
9,mart_route_performance,route_end_date,DATE,241,0,168,2025-10-27,2026-10-17,0.0
10,mart_route_performance,route_status,VARCHAR,241,0,4,ALTA,UNKNOWN,0.0
11,mart_route_performance,total_visits,BIGINT,241,0,31,0,35,0.0
12,mart_route_performance,reference_date,DATE,241,0,1,2026-05-19,2026-05-19,0.0
13,mart_route_performance,is_closed,BOOLEAN,241,0,2,false,true,0.0
14,mart_route_performance,is_closed_without_visits,BOOLEAN,241,0,2,false,true,0.0
15,mart_route_performance,days_since_closed,BIGINT,241,203,35,6,204,84.2

                     model       column      test to
65  mart_route_performance  campaign_id  not_null
66  mart_route_performance     route_id  not_null
67  mart_route_performance     route_id    unique

In [18]:
# days null by flag
run_sql("""
    select is_closed_without_visits, count(*) as routes,
           count(*) filter (where days_since_closed is null) as days_null
    from marts.mart_route_performance
    group by 1
""")

   is_closed_without_visits  routes  days_null
0                     False     203        203
1                      True      38          0

In [19]:
# null code and name
run_sql("""
    select count(*) filter (where route_code is null) as code_null,
           count(*) filter (where route_name is null) as name_null,
           count(*) filter (where route_code is null and route_name is null) as both_null,
           count(*) filter (where route_code <> 'RUT' || lpad(route_id::varchar, 5, '0')) as code_not_id,
           count(*) filter (where route_name <> 'Ruta ' || route_id) as name_not_id
    from marts.mart_route_performance
""")

   code_null  name_null  both_null  code_not_id  name_not_id
0         12          8          1            0            0

In [20]:
# status values
count_values(MARTS, "mart_route_performance", "route_status")

       value  rows   pct
0    UNKNOWN    78  32.4
1  PENDIENTE    61  25.3
2       ALTA    60  24.9
3       BAJA    42  17.4

In [21]:
# zero visit routes
run_sql("""
    select route_status, count(*) as routes,
           count(*) filter (where total_visits = 0) as zero_visits,
           count(*) filter (where is_closed_without_visits) as closed_zero,
           count(*) filter (where total_visits = 0 and not is_closed) as open_zero
    from marts.mart_route_performance
    group by 1
    order by 2 desc
""")

  route_status  routes  zero_visits  closed_zero  open_zero
0      UNKNOWN      78           12           12          0
1    PENDIENTE      61            8            7          1
2         ALTA      60           12           10          2
3         BAJA      42            9            9          0

In [22]:
# check key nulls
check_nulls(MARTS, "mart_route_performance", [
    "route_id", "campaign_id", "route_start_date", "route_end_date", "route_status", "total_visits",
    "route_code", "route_name", "days_since_closed",
])

                    table             column  nulls status
0  mart_route_performance           route_id      0     OK
1  mart_route_performance        campaign_id      0     OK
2  mart_route_performance   route_start_date      0     OK
3  mart_route_performance     route_end_date      0     OK
4  mart_route_performance       route_status      0     OK
5  mart_route_performance       total_visits      0     OK
6  mart_route_performance         route_code     12   FAIL
7  mart_route_performance         route_name      8   FAIL
8  mart_route_performance  days_since_closed    203   FAIL

### mart_worker_performance

In [23]:
show_table(MARTS, "mart_worker_performance")

,employee_id,employee_first_name,employee_address_province,routes_as_main,visits_recorded,visits_done,active_days,visits_per_active_day
0,8,Carlos,CASTELLON,5,57,46,46,1.00
1,19,Isabel,CANILLO,8,45,38,34,1.12
2,22,José,PORTALEGRE,6,29,24,25,0.96
3,32,Javier,ASTURIAS,8,62,58,39,1.49
4,24,Sara,CASTELLON,10,42,39,35,1.11

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,mart_worker_performance,employee_id,INTEGER,34,0,34,1,45,0.0
1,mart_worker_performance,employee_first_name,VARCHAR,34,0,14,Ana,Sara,0.0
2,mart_worker_performance,employee_address_province,VARCHAR,34,1,25,A CORUNA,ZAMORA,2.9
3,mart_worker_performance,routes_as_main,BIGINT,34,0,9,3,11,0.0
4,mart_worker_performance,visits_recorded,BIGINT,34,0,29,13,121,0.0
5,mart_worker_performance,visits_done,BIGINT,34,0,27,10,107,0.0
6,mart_worker_performance,active_days,BIGINT,34,0,27,13,82,0.0
7,mart_worker_performance,visits_per_active_day,DOUBLE,34,0,27,0.77,1.69,0.0

                      model       column      test to
72  mart_worker_performance  employee_id  not_null
73  mart_worker_performance  employee_id    unique

### mart_visit_responses

In [24]:
show_table(MARTS, "mart_visit_responses")

,answer_id,visit_id,client_name,project_name,project_type,campaign_id,campaign_name,visit_date,visit_month,visit_status,...,intervention_point_name,intervention_point_province,question_id,question_name,question_category,question_type,question_is_highlighted,answer,wants_to_order,accepts_training
0,1,1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-02,2026-01-01,INFO,...,CONDIS 56,None,4,¿Se ha realizado toda la instalación del vinil...,2.Visita,S,False,"No, rechazan la instalación",<NA>,<NA>
1,2,1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-02,2026-01-01,INFO,...,CONDIS 56,None,12,Tipo de farmacia,1. Visita,T,False,Sin comentarios,<NA>,<NA>
2,3,1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-02,2026-01-01,INFO,...,CONDIS 56,None,8,Indica el nº de facings de Reflex Gel,2. Visibilidad,S,False,"0, No tienen stock",<NA>,<NA>
3,4,1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-02,2026-01-01,INFO,...,CONDIS 56,None,6,Indica el nº de facings de Nurofen,2. Visibilidad,S,True,"0, No esta expuesto",<NA>,<NA>
4,5,1,Laboratorios Valtera España,Proyecto Mantenimiento 1,Mantenimiento,1,Campaña Oct 2025 – Proyecto Mantenimiento 1,2026-01-02,2026-01-01,INFO,...,CONDIS 56,None,5,Que producto en concreto?,1. Visita,T,False,Auxiliar de farmacia,<NA>,<NA>

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,mart_visit_responses,answer_id,INTEGER,10192,0,10192,1,10192,0.0
1,mart_visit_responses,visit_id,INTEGER,10192,0,1747,1,1747,0.0
2,mart_visit_responses,client_name,VARCHAR,10192,0,13,Aquilea Consumer Health,Vitahealth España,0.0
3,mart_visit_responses,project_name,VARCHAR,10192,0,27,Proyecto Auditoria 15,Proyecto Visibilidad 8,0.0
4,mart_visit_responses,project_type,VARCHAR,10192,0,5,Auditoria,Visibilidad,0.0
5,mart_visit_responses,campaign_id,INTEGER,10192,0,64,1,72,0.0
6,mart_visit_responses,campaign_name,VARCHAR,10192,0,53,Campaña Dec 2025 – Proyecto Auditoria 15,Campaña Oct 2025 – Proyecto Visibilidad 4,0.0
7,mart_visit_responses,visit_date,DATE,10192,201,139,2026-01-01,2026-05-19,2.0
8,mart_visit_responses,visit_month,DATE,10192,201,5,2026-01-01,2026-05-01,2.0
9,mart_visit_responses,visit_status,VARCHAR,10192,0,5,INCID,UNKNOWN,0.0
10,mart_visit_responses,intervention_point_id,INTEGER,10192,0,248,1,250,0.0
11,mart_visit_responses,intervention_point_name,VARCHAR,10192,283,242,AROMAS 127,SUPERMERCADOS MIRANDA 89,2.8
12,mart_visit_responses,intervention_point_province,VARCHAR,10192,520,46,A CORUNA,ZARAGOZA,5.1
13,mart_visit_responses,question_id,INTEGER,10192,288,564,1,648,2.8
14,mart_visit_responses,question_name,VARCHAR,10192,568,26,CONTACTO VISITA,¿Se ha realizado toda la instalación del vinil...,5.6
15,mart_visit_responses,question_category,VARCHAR,10192,1083,4,1. Visita,2.Visita,10.6
16,mart_visit_responses,question_type,VARCHAR,10192,44,4,M,T,0.4
17,mart_visit_responses,question_is_highlighted,BOOLEAN,10192,288,2,false,true,2.8
18,mart_visit_responses,answer,VARCHAR,10192,1025,67,"0, No esta expuesto",Visita OK,10.1
19,mart_visit_responses,wants_to_order,BOOLEAN,10192,9857,2,false,true,96.7
20,mart_visit_responses,accepts_training,BOOLEAN,10192,9922,2,false,true,97.4

                   model         column               test to
68  mart_visit_responses      answer_id           not_null
69  mart_visit_responses      answer_id             unique
70  mart_visit_responses  question_type    accepted_values
71  mart_visit_responses            NaN  row_count_matches

### Null audit

Marts keep the nulls of the source. Joins are LEFT and do not create nulls.

In [25]:
# raw vs mart nulls
run_sql("""
    select 'responses.question_id' as col,
           (select count(*) filter (where question_id is null) from raw.raw_responses) as raw_nulls,
           (select count(*) filter (where question_id is null) from marts.fct_responses) as mart_nulls
    union all
    select 'responses.answer',
           (select count(*) filter (where answer is null) from raw.raw_responses),
           (select count(*) filter (where answer is null) from marts.fct_responses)
    union all
    select 'responses.question_type',
           (select count(*) filter (where question_type is null) from raw.raw_responses),
           (select count(*) filter (where question_type is null) from marts.fct_responses)
    union all
    select 'visits.visit_type',
           (select count(*) filter (where visit_type is null) from raw.raw_visits),
           (select count(*) filter (where visit_type is null) from marts.fct_visits)
    union all
    select 'visits.visit_time',
           (select count(*) filter (where visit_time is null) from raw.raw_visits),
           (select count(*) filter (where visit_time is null) from marts.fct_visits)
    union all
    select 'visits.is_client_billable',
           (select count(*) filter (where is_client_billable is null) from raw.raw_visits),
           (select count(*) filter (where is_client_billable is null) from marts.fct_visits)
    union all
    select 'campaign.visit_duration_minutes',
           (select count(*) filter (where visit_duration_minutes is null) from raw.raw_campaigns),
           (select count(*) filter (where visit_duration_minutes is null) from marts.dim_campaign)
""")

                               col  raw_nulls  mart_nulls
0            responses.question_id        288         288
1                 responses.answer       1025        1025
2          responses.question_type        509         509
3                visits.visit_type        666         664
4                visits.visit_time        180         179
5        visits.is_client_billable        107         105
6  campaign.visit_duration_minutes         13          13

In [26]:
# join orphans
run_sql("""
    select
        count(*) filter (where dc.campaign_id is null) as no_campaign,
        count(*) filter (where dp.intervention_point_id is null) as no_pos,
        count(*) filter (where fr.question_id is not null and dq.question_id is null) as orphan_question,
        count(*) filter (where fr.question_id is null) as answers_without_question
    from marts.fct_responses as fr
    left join marts.dim_campaign as dc on fr.campaign_id = dc.campaign_id
    left join marts.dim_pos as dp on fr.intervention_point_id = dp.intervention_point_id
    left join marts.dim_question as dq on fr.question_id = dq.question_id
""")

   no_campaign  no_pos  orphan_question  answers_without_question
0            0       0                0                       288

In [27]:
# worker null reasons
run_sql("""
    select count(*) filter (where employee_id is null) as no_worker,
           count(*) filter (where employee_id is null and route_id = -1) as no_route,
           count(*) filter (where employee_id is null and route_id <> -1) as route_without_main
    from marts.fct_visits
""")

   no_worker  no_route  route_without_main
0        252       225                  27

### Missing tables

In [28]:
documented = ["dim_client", "dim_project", "dim_campaign", "dim_pos", "dim_route", "dim_worker", "dim_question", "bridge_route_worker", "fct_visits", "fct_responses", "mart_campaign_performance", "mart_pos_coverage", "mart_route_performance", "mart_worker_performance", "mart_visit_responses"]
sorted(set(show_tables(MARTS)["name"]) ^ set(documented))

[]