# EDA - Primer Impacto data analyst test

Exploratory analysis of the 10 raw csv files.

## Setup

In [1]:
from pathlib import Path

import pandas as pd

RAW_DIR = Path("../data/raw")
csv_paths = sorted(RAW_DIR.glob("*.csv"))
raw_tables = {path.stem: pd.read_csv(path) for path in csv_paths}
list(raw_tables.keys())

['raw_campaigns',
 'raw_clients',
 'raw_pos',
 'raw_projects',
 'raw_questions',
 'raw_responses',
 'raw_route_employee',
 'raw_routes',
 'raw_visits',
 'raw_workers']

## summarize_table

One function, same checks for every table below, so results are easy to
compare across the 10 raw csvs.

In [2]:
def summarize_table(df: pd.DataFrame, pk: str) -> None:
    """Run the standard eda checks for one raw table."""
    df.info()
    display(df.head())

    null_counts = df.isna().sum()
    print("nulls per column:")
    print(null_counts[null_counts > 0])

    dup_pk = df[pk].duplicated().sum()
    print(f"pk={pk} unique={df[pk].nunique()} rows={len(df)} dup_pk={dup_pk}")

    str_cols = df.select_dtypes(include="str").columns
    print("distinct values per text column:")
    print({col: df[col].nunique() for col in str_cols})

## Per table EDA

#### raw_clients

In [3]:
summarize_table(raw_tables["raw_clients"], pk="client_id")

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   client_id       15 non-null     int64
 1   client_name     15 non-null     str
 2   company_id      15 non-null     int64
 3   country         15 non-null     str
 4   sector          15 non-null     str
 5   created_at      15 non-null     str
 6   updated_at_sys  15 non-null     str
dtypes: int64(2), str(5)
memory usage: 972.0 bytes

,client_id,client_name,company_id,country,sector,created_at,updated_at_sys
0,1,Laboratorios Valtera España,1,spain,Farma,2021-10-17,2023-06-13
1,2,Pharmakon Consumer Health,1,España,Farma,2020-05-14,2021-08-04
2,3,Medicolab Iberia,1,spain,Farma,2019-04-22,2022-06-14
3,4,Biofarma España SL,1,spain,Gran Consumo,2019-02-12,2020-05-08
4,5,Salutis Consumer España,1,España,Farma,2020-07-08,2021-05-30

nulls per column:
Series([], dtype: int64)
pk=client_id unique=14 rows=15 dup_pk=1
distinct values per text column:
{'client_name': 14, 'country': 3, 'sector': 3, 'created_at': 13, 'updated_at_sys': 14}

#### raw_projects

In [4]:
summarize_table(raw_tables["raw_projects"], pk="project_id")

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   project_id          28 non-null     int64
 1   project_name        28 non-null     str
 2   project_code        26 non-null     str
 3   client_id           28 non-null     int64
 4   client_code         28 non-null     str
 5   created_at          28 non-null     str
 6   updated_at_sys      28 non-null     str
 7   project_exportable  28 non-null     bool
dtypes: bool(1), int64(2), str(5)
memory usage: 1.7 KB

,project_id,project_name,project_code,client_id,client_code,created_at,updated_at_sys,project_exportable
0,1,Proyecto Mantenimiento 1,PRJ0001,1,CLI0001,2024-09-30,2024-11-05,False
1,2,Proyecto Formación 2,PRJ0002,2,CLI0002,2024-09-07,2025-01-23,False
2,3,Proyecto Visibilidad 3,PRJ0003,2,CLI0002,2024-11-28,2025-05-08,True
3,4,Proyecto Visibilidad 4,PRJ0004,2,CLI0002,2024-10-01,2025-12-23,True
4,5,Proyecto Auditoria 5,PRJ0005,3,CLI0003,2025-05-26,2025-07-01,True

nulls per column:
project_code    2
dtype: int64
pk=project_id unique=28 rows=28 dup_pk=0
distinct values per text column:
{'project_name': 28, 'project_code': 26, 'client_code': 14, 'created_at': 27, 'updated_at_sys': 27}

#### raw_campaigns

In [5]:
summarize_table(raw_tables["raw_campaigns"], pk="campaign_id")

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   campaign_id             72 non-null     int64
 1   campaign_code           70 non-null     str
 2   campaign_name           72 non-null     str
 3   project_id              72 non-null     int64
 4   project_code            65 non-null     str
 5   client_code             72 non-null     str
 6   campaign_start_date     72 non-null     str
 7   campaign_end_date       72 non-null     str
 8   is_active               67 non-null     object
 9   campaign_state_id       72 non-null     int64
 10  campaign_state          59 non-null     str
 11  total_visits_planned    72 non-null     int64
 12  total_pos_planned       72 non-null     int64
 13  visit_duration_minutes  59 non-null     float64
 14  created_at              72 non-null     str
 15  updated_at_sys          72 non-null     str
dtypes: float64(1), int64(5), object(1), str(9)
memory usage: 9.1+ KB

,campaign_id,campaign_code,campaign_name,project_id,project_code,client_code,campaign_start_date,campaign_end_date,is_active,campaign_state_id,campaign_state,total_visits_planned,total_pos_planned,visit_duration_minutes,created_at,updated_at_sys
0,1,CAM00001,Campaña Oct 2025 – Proyecto Mantenimiento 1,1,PRJ0001,CLI0001,20/10/2025,12/03/2026,False,5,Activa,141,52,45.0,2025-09-30,2025-12-13
1,2,CAM00002,Campaña Jan 2026 – Proyecto Mantenimiento 1,1,PRJ0001,CLI0001,2026-01-11,2026-02-25,False,4,En preparación,376,197,60.0,2025-12-15,2026-03-14
2,3,CAM00003,Campaña Nov 2025 – Proyecto Formación 2,2,PRJ0002,CLI0002,2025-11-18,2026-03-03,False,1,NaN,45,159,45.0,2025-10-28,2025-12-28
3,4,CAM00004,Campaña Oct 2025 – Proyecto Formación 2,2,PRJ0002,CLI0002,2025-10-15,2026-03-24,False,2,Pausada,311,73,60.0,2025-10-09,2026-03-22
4,5,CAM00005,Campaña Jan 2026 – Proyecto Visibilidad 3,3,PRJ0003,CLI0002,2026-01-16,2026-07-14,True,3,Cerrada,222,43,30.0,2026-01-01,2026-04-22

nulls per column:
campaign_code              2
project_code               7
is_active                  5
campaign_state            13
visit_duration_minutes    13
dtype: int64
pk=campaign_id unique=72 rows=72 dup_pk=0
distinct values per text column:
{'campaign_code': 70, 'campaign_name': 59, 'project_code': 26, 'client_code': 14, 'campaign_start_date': 62, 'campaign_end_date': 64, 'campaign_state': 4, 'created_at': 55, 'updated_at_sys': 60}

#### raw_questions

In [6]:
summarize_table(raw_tables["raw_questions"], pk="question_id")

<class 'pandas.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   question_id              648 non-null    int64
 1   campaign_id              648 non-null    int64
 2   campaign_code            648 non-null    str
 3   question_code            602 non-null    str
 4   question_name            630 non-null    str
 5   question_type            620 non-null    str
 6   question_category        594 non-null    str
 7   question_order           625 non-null    float64
 8   question_is_highlighted  648 non-null    bool
 9   image_associated         648 non-null    bool
 10  created_at               648 non-null    str
 11  updated_at_sys           648 non-null    str
dtypes: bool(2), float64(1), int64(2), str(7)
memory usage: 52.0 KB

,question_id,campaign_id,campaign_code,question_code,question_name,question_type,question_category,question_order,question_is_highlighted,image_associated,created_at,updated_at_sys
0,1,1,CAM00001,Q00001,En caso de hacer una mejora en Strepsils/Stref...,M,2. Visibilidad,1.0,False,False,2025-09-30,2026-01-24
1,2,1,CAM00001,Q00002,"En caso de hacer una mejora en Nurofen, indícalo",M,2. Visibilidad,2.0,False,False,2025-09-30,2025-10-25
2,3,1,CAM00001,Q00003,Indica el nº de facings de Reflex Spray,S,2. Visibilidad,3.0,False,True,2025-09-30,2026-03-25
3,4,1,CAM00001,Q00004,¿Se ha realizado toda la instalación del vinil...,S,2.Visita,4.0,False,True,2025-09-30,2026-04-09
4,5,1,CAM00001,Q00005,Que producto en concreto?,T,1. Visita,5.0,False,False,2025-09-30,2025-11-01

nulls per column:
question_code        46
question_name        18
question_type        28
question_category    54
question_order       23
dtype: int64
pk=question_id unique=648 rows=648 dup_pk=0
distinct values per text column:
{'campaign_code': 72, 'question_code': 602, 'question_name': 26, 'question_type': 4, 'question_category': 4, 'created_at': 55, 'updated_at_sys': 200}

#### raw_workers

In [7]:
summarize_table(raw_tables["raw_workers"], pk="employee_id")

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   employee_id                47 non-null     int64
 1   employee_first_name        47 non-null     str
 2   employee_active_status     44 non-null     object
 3   employee_hire_date         45 non-null     str
 4   employee_address_province  46 non-null     str
 5   employee_contract_type     33 non-null     str
 6   company_id                 47 non-null     int64
 7   created_at                 47 non-null     str
 8   updated_at_sys             47 non-null     str
dtypes: int64(2), object(1), str(6)
memory usage: 3.4+ KB

,employee_id,employee_first_name,employee_active_status,employee_hire_date,employee_address_province,employee_contract_type,company_id,created_at,updated_at_sys
0,1,David,True,2018-12-23,Castelló,NaN,1,2018-12-23,2025-06-14
1,2,Claudia,True,2021-07-02,Guarda,PART,1,2021-07-02,2023-12-22
2,3,Laura,True,2019-04-27,Canillo,INDEF,1,2019-04-27,2025-05-27
3,4,Elena,True,2021-12-05,Castellon,TEMP,1,2021-12-05,2022-04-29
4,5,Pablo,False,2021-06-29,MÁLAGA,INDEF,1,2021-06-29,2023-08-23

nulls per column:
employee_active_status        3
employee_hire_date            2
employee_address_province     1
employee_contract_type       14
dtype: int64
pk=employee_id unique=45 rows=47 dup_pk=2
distinct values per text column:
{'employee_first_name': 14, 'employee_hire_date': 43, 'employee_address_province': 33, 'employee_contract_type': 3, 'created_at': 45, 'updated_at_sys': 45}

#### raw_pos

In [8]:
summarize_table(raw_tables["raw_pos"], pk="intervention_point_id")

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   intervention_point_id           250 non-null    int64
 1   intervention_point_code         236 non-null    str
 2   intervention_point_name         244 non-null    str
 3   intervention_point_address      235 non-null    str
 4   intervention_point_province     236 non-null    str
 5   intervention_point_locality     224 non-null    str
 6   intervention_point_postal_code  224 non-null    float64
 7   intervention_point_latitude     235 non-null    float64
 8   intervention_point_longitude    243 non-null    float64
 9   intervention_point_is_active    240 non-null    object
 10  created_at                      250 non-null    str
 11  updated_at                      250 non-null    str
dtypes: float64(3), int64(1), object(1), str(7)
memory usage: 23.6+ KB

,intervention_point_id,intervention_point_code,intervention_point_name,intervention_point_address,intervention_point_province,intervention_point_locality,intervention_point_postal_code,intervention_point_latitude,intervention_point_longitude,intervention_point_is_active,created_at,updated_at
0,1,PDV000001,CONDISLIFE EL TEU SÚPER 1,Calle 20 Nº 41,GUADALAJARA,Localidad 50,46365.0,41.774104,-5.411961,True,2020-05-07,2025-01-26
1,2,PDV000002,CONDIS EL TEU SÚPER 2,Calle 68 Nº 12,"Palmas, Las",Localidad 32,40996.0,37.338316,-7.198834,False,2023-06-11,2025-10-20
2,3,PDV000003,CEPSA 3,Calle 27 Nº 3,Asturias,Localidad 37,17423.0,39.344115,-6.713749,True,2023-09-23,2025-02-03
3,4,PDV000004,CEPSA 4,NaN,Évora,Localidad 46,33157.0,39.270433,0.871244,NaN,2022-02-26,2025-12-06
4,5,PDV000005,DIA % MARKET 5,Calle 146 Nº 35,CÁCERES,Localidad 44,NaN,40.742044,-7.411996,True,2022-07-30,2026-02-17

nulls per column:
intervention_point_code           14
intervention_point_name            6
intervention_point_address        15
intervention_point_province       14
intervention_point_locality       26
intervention_point_postal_code    26
intervention_point_latitude       15
intervention_point_longitude       7
intervention_point_is_active      10
dtype: int64
pk=intervention_point_id unique=250 rows=250 dup_pk=0
distinct values per text column:
{'intervention_point_code': 236, 'intervention_point_name': 244, 'intervention_point_address': 234, 'intervention_point_province': 59, 'intervention_point_locality': 50, 'created_at': 228, 'updated_at': 215}

#### raw_routes

In [9]:
summarize_table(raw_tables["raw_routes"], pk="route_id")

<class 'pandas.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   route_id          241 non-null    int64
 1   route_code        229 non-null    str
 2   route_name        233 non-null    str
 3   campaign_id       241 non-null    int64
 4   campaign_code     241 non-null    str
 5   route_start_date  241 non-null    str
 6   route_end_date    241 non-null    str
 7   route_status      163 non-null    str
 8   delegation_code   214 non-null    str
 9   recall_mail_sent  241 non-null    bool
 10  created_at        241 non-null    str
 11  updated_at_sys    241 non-null    str
dtypes: bool(1), int64(2), str(9)
memory usage: 21.1 KB

,route_id,route_code,route_name,campaign_id,campaign_code,route_start_date,route_end_date,route_status,delegation_code,recall_mail_sent,created_at,updated_at_sys
0,1,NaN,Ruta 1,1,CAM00001,2026-01-01,2026-03-01,NaN,DLG15,True,2025-12-26,2026-04-03
1,2,RUT00002,Ruta 2,1,CAM00001,2026-01-18,2026-04-10,NaN,DLG04,True,2026-01-15,2026-02-02
2,3,RUT00003,Ruta 3,1,CAM00001,2026-03-31,2026-05-13,Alta,DLG07,True,2026-03-29,2026-05-12
3,4,RUT00004,Ruta 4,2,CAM00002,2026-01-13,2026-02-19,Alta,DLG06,True,2026-01-09,2026-01-22
4,5,RUT00005,Ruta 5,2,CAM00002,2026-01-11,2026-02-23,Baja,DLG12,False,2026-01-03,2026-04-26

nulls per column:
route_code         12
route_name          8
route_status       78
delegation_code    27
dtype: int64
pk=route_id unique=241 rows=241 dup_pk=0
distinct values per text column:
{'route_code': 229, 'route_name': 233, 'campaign_code': 72, 'route_start_date': 134, 'route_end_date': 168, 'route_status': 3, 'delegation_code': 15, 'created_at': 128, 'updated_at_sys': 122}

#### raw_route_employee

In [10]:
summarize_table(raw_tables["raw_route_employee"], pk="route_employee_id")

<class 'pandas.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   route_employee_id  482 non-null    int64
 1   route_id           482 non-null    int64
 2   employee_id        482 non-null    int64
 3   main_employee      482 non-null    bool
 4   ip_percentage      468 non-null    float64
 5   created_at         482 non-null    str
 6   updated_at         482 non-null    str
 7   deleted_at         25 non-null     str
dtypes: bool(1), float64(1), int64(3), str(3)
memory usage: 27.0 KB

,route_employee_id,route_id,employee_id,main_employee,ip_percentage,created_at,updated_at,deleted_at
0,1,1,32,True,100.0,2025-12-26,2026-04-03,NaN
1,2,1,44,False,19.0,2025-12-26,2026-04-03,NaN
2,3,2,19,True,100.0,2026-01-15,2026-02-02,NaN
3,4,2,35,False,44.8,2026-01-15,2026-02-02,NaN
4,5,3,44,True,100.0,2026-03-29,2026-05-12,2026-04-14

nulls per column:
ip_percentage     14
deleted_at       457
dtype: int64
pk=route_employee_id unique=482 rows=482 dup_pk=0
distinct values per text column:
{'created_at': 128, 'updated_at': 122, 'deleted_at': 24}

#### raw_visits

In [11]:
summarize_table(raw_tables["raw_visits"], pk="visit_id")

<class 'pandas.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   visit_id                 1762 non-null   int64
 1   campaign_id              1762 non-null   int64
 2   campaign_code            1762 non-null   str
 3   project_code             1762 non-null   str
 4   intervention_point_id    1762 non-null   int64
 5   intervention_point_code  1667 non-null   str
 6   route_id                 1606 non-null   float64
 7   route_code               1628 non-null   str
 8   visit_date               1725 non-null   str
 9   visit_time               1582 non-null   str
 10  visit_status             1691 non-null   str
 11  visit_type               1096 non-null   str
 12  is_client_billable       1655 non-null   object
 13  created_at               1762 non-null   str
 14  updated_at_sys           1762 non-null   str
dtypes: float64(1), int64(3), object(1), str(10)
memory usage: 206.6+ KB

,visit_id,campaign_id,campaign_code,project_code,intervention_point_id,intervention_point_code,route_id,route_code,visit_date,visit_time,visit_status,visit_type,is_client_billable,created_at,updated_at_sys
0,1,1,CAM00001,PRJ0001,56,PDV000056,3.0,RUT00003,2026-01-02,18:15:00,INFO,NaN,True,2025-12-31,2026-02-16
1,2,1,CAM00001,PRJ0001,36,PDV000036,3.0,RUT00003,2026-02-05,12:30:00,INCID,NaN,False,2026-02-03,2026-05-14
2,3,1,CAM00001,PRJ0001,116,PDV000116,3.0,RUT00003,2026-03-08,17:15:00,INCID,C,True,2026-03-04,2026-05-17
3,4,1,CAM00001,PRJ0001,24,PDV000024,3.0,NaN,2026-02-04,16:15:00,INCID,C,False,2026-01-30,2026-04-20
4,5,1,CAM00001,PRJ0001,83,NaN,3.0,RUT00003,2026-01-05,13:30:00,NOVIS,C,True,2026-01-01,2026-02-21

nulls per column:
intervention_point_code     95
route_id                   156
route_code                 134
visit_date                  37
visit_time                 180
visit_status                71
visit_type                 666
is_client_billable         107
dtype: int64
pk=visit_id unique=1747 rows=1762 dup_pk=15
distinct values per text column:
{'campaign_code': 64, 'project_code': 32, 'intervention_point_code': 248, 'route_code': 270, 'visit_date': 242, 'visit_time': 48, 'visit_status': 4, 'visit_type': 3, 'created_at': 144, 'updated_at_sys': 130}

#### raw_responses

In [12]:
summarize_table(raw_tables["raw_responses"], pk="answer_id")

<class 'pandas.DataFrame'>
RangeIndex: 10192 entries, 0 to 10191
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   answer_id                10192 non-null  int64
 1   visit_id                 10192 non-null  int64
 2   question_id              9904 non-null   float64
 3   campaign_code            10192 non-null  str
 4   intervention_point_code  9611 non-null   str
 5   question_type            9683 non-null   str
 6   answer                   9167 non-null   str
 7   expected_answer          3341 non-null   str
 8   created_at               10192 non-null  str
 9   updated_at_sys           10192 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 796.4 KB

,answer_id,visit_id,question_id,campaign_code,intervention_point_code,question_type,answer,expected_answer,created_at,updated_at_sys
0,1,1,4.0,CAM00001,PDV000056,S,"No, rechazan la instalación",Si,2025-12-31,2026-02-16
1,2,1,12.0,CAM00001,PDV000056,T,Sin comentarios,Si,2025-12-31,2026-02-16
2,3,1,8.0,CAM00001,PDV000056,S,"0, No tienen stock",Si,2025-12-31,2026-02-16
3,4,1,6.0,CAM00001,PDV000056,S,"0, No esta expuesto",No,2025-12-31,2026-02-16
4,5,1,5.0,CAM00001,PDV000056,T,Auxiliar de farmacia,No,2025-12-31,2026-02-16

nulls per column:
question_id                 288
intervention_point_code     581
question_type               509
answer                     1025
expected_answer            6851
dtype: int64
pk=answer_id unique=10192 rows=10192 dup_pk=0
distinct values per text column:
{'campaign_code': 64, 'intervention_point_code': 248, 'question_type': 4, 'answer': 128, 'expected_answer': 2, 'created_at': 144, 'updated_at_sys': 130}

## Data quality issues

At least three issues found during the EDA above, with real evidence and
the proposed fix:

1. **Duplicate primary keys**: `raw_clients.client_id`, `raw_workers.employee_id`
   and `raw_visits.visit_id` all have exact duplicate rows (e.g. visit_id 20
   appears twice, same data). Staging must deduplicate with a distinct or a
   row_number over the natural key before using it as a join key.
2. **Inconsistent country and province casing**: `raw_clients.country` has
   `spain`, `SPAIN` and `España` for the same value, just casing, verified
   at byte level, not an encoding bug. `raw_pos.intervention_point_province`
   mixes case and includes a non spanish province (`Évora`, Portugal). Fix
   with trim and uppercase, same pattern as `clean_string` in the reference
   dbt project.
3. **Mixed date formats**: `raw_campaigns.campaign_start_date` has 12 rows in
   `dd/mm/yyyy` format while the rest are `yyyy-mm-dd`. Staging must parse
   both formats explicitly before casting to date, otherwise pandas or dbt
   will silently misread day and month.
4. **Soft deletes not filtered**: `raw_route_employee` has a `deleted_at`
   column, rows are not physically removed. Staging must filter
   `deleted_at is null` unless historical rows are needed on purpose.
5. **Unexpected column not documented**: `raw_responses` has an
   `expected_answer` column not mentioned in the README, worth checking if
   it should feed a correctness metric on worker answers.

## Star schema proposal

Grain and dimensions proposed from the data model:

- **dim_client**, **dim_project**, **dim_campaign**: one row per entity,
  campaign carries the date range and planned visits.
- **dim_pos**: one row per intervention point (province, location).
- **dim_worker**: one row per employee.
- **dim_question**: one row per question, campaign and category.
- **dim_route**: one row per route, campaign and dates.
- **fct_visits**: grain is one row per visit. Foreign keys to campaign, pos,
  route. Measures like visit status and planned versus done.
- **fct_responses**: grain is one row per answer. Foreign keys to visit and
  question, this is the table that feeds the dashboard KPIs on completion
  and answer quality.

Two fact tables because visits and responses have a different grain, one
visit can have many responses.