# Marts

In [1]:
# setup
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path("..").resolve()
load_dotenv(ROOT / ".env")
MARTS = "marts"

In [2]:
# functions
%run -i utils/inspect_functions.ipynb

### Summary

In [3]:
show_tables(MARTS)

                    name        type  columns  rows
0           dim_campaign  BASE TABLE        7    17
1               dim_date  BASE TABLE        7   699
2                dim_pos  BASE TABLE       16   411
3              dim_route  BASE TABLE        5   296
4       dim_visit_status  BASE TABLE        4     5
5  fct_campaign_progress  BASE TABLE        6    16
6             fct_visits  BASE TABLE       10   480

In [4]:
find_keys(profile_columns(MARTS))

              table_name   column_name     type  rows
0           dim_campaign  campaign_key  integer    17
1               dim_date      date_key  integer   699
2                dim_pos       pos_key     text   411
3              dim_route     route_key  integer   296
4       dim_visit_status    status_key  integer     5
5  fct_campaign_progress  campaign_key  integer    16
6             fct_visits      visit_id  integer   480

In [5]:
show_nulls(MARTS)

      table_name            column_name  nulls  rows  null_pct
0   dim_campaign    campaign_start_date      1    17       5.9
1   dim_campaign      campaign_end_date      1    17       5.9
2       dim_date               date_day      1   699       0.1
3       dim_date                   year      1   699       0.1
4       dim_date                  month      1   699       0.1
5       dim_date                   week      1   699       0.1
6       dim_date            day_of_week      1   699       0.1
7        dim_pos  intervention_point_id     46   411      11.2
8        dim_pos                 ext_id    166   411      40.4
9        dim_pos                 street      1   411       0.2
10       dim_pos            door_number      1   411       0.2
11       dim_pos               province     46   411      11.2
12       dim_pos               latitude     46   411      11.2
13       dim_pos              longitude     46   411      11.2
14       dim_pos             match_rule    211   411      51.3
15       dim_pos             confidence    211   411      51.3
16     dim_route       route_start_date      1   296       0.3
17     dim_route         route_end_date      1   296       0.3

In [6]:
check_text(MARTS)

,table,text_columns,edge_spaces,extra_spaces,empty_strings,status
0,dim_campaign,3,0,0,0,OK
1,dim_pos,10,0,0,0,OK
2,dim_route,1,0,0,0,OK
3,dim_visit_status,1,0,0,0,OK
4,fct_visits,1,0,0,0,OK

### Unknown row per dimension

In [7]:
run_sql("""
    select 'dim_pos' as dim, count(*) as unknown_rows from marts.dim_pos where pos_key = '-1'
    union all select 'dim_campaign', count(*) from marts.dim_campaign where campaign_key = -1
    union all select 'dim_route', count(*) from marts.dim_route where route_key = -1
    union all select 'dim_date', count(*) from marts.dim_date where date_key = -1
    union all select 'dim_visit_status', count(*) from marts.dim_visit_status where status_key = -1
""")

                dim  unknown_rows
0           dim_pos             1
1      dim_campaign             1
2         dim_route             1
3          dim_date             1
4  dim_visit_status             1

### dim_pos

In [8]:
show_table(MARTS, "dim_pos")

,pos_key,intervention_point_id,ext_id,name,name_normalized,street,door_number,postal_code,province,latitude,longitude,is_active,match_status,source_system,match_rule,confidence
0,6c3158da42239212b475c868bbc9ca4d,1,NaN,NutriSalud Estación 1,nutrisalud estación 1,Calle 40,105,36371,PONTEVEDRA,41.368505,-2.314403,True,OMNI_ONLY,OMNI,NaN,NaN
1,828b91d3e5dc0cc19d6b3426e00cb0e7,2,GI-090095,Parafarma Look Bulevar 2,parafarma look bulevar 2,Calle 86,98,50338,CANTABRIA,40.382110,-4.183453,True,MATCHED,OMNI+GI,NAME_POSTAL_CODE,1.0
2,8c16797dd91a1a0fe9f208a5b38f4a61,3,GI-090023,FarmaVida Estación 3,farmavida estación 3,Calle 37,54,48009,GIRONA,40.671294,-5.239660,True,MATCHED,OMNI+GI,NAME_POSTAL_CODE,1.0
3,4269cff7a94959e5e21e912de3d6befa,4,GI-090057,Herbolario Natura Avenida 4,herbolario natura avenida 4,Calle 87,55,41010,MURCIA,42.111763,2.793883,True,MATCHED,OMNI+GI,NAME_ADDRESS,0.8
4,a81916fce3e4a2d21c803f3b845b4a00,5,GI-090070,BioPharma Plus Norte 5,biopharma plus norte 5,Calle 37,132,31966,GRANADA,36.719081,2.695196,False,MATCHED,OMNI+GI,NAME_POSTAL_CODE,1.0

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_pos,pos_key,text,411,0,411,00e1fbb665073c505a2f41a05513b7b9,fffbea3800ecb4472fca636dd7025fcd,0.0
1,dim_pos,intervention_point_id,integer,411,46,365,1,365,11.2
2,dim_pos,ext_id,text,411,166,245,GI-090001,GI-090245,40.4
3,dim_pos,name,text,411,0,411,BioPharma Plus Avenida 249,Vitalia Farma Sur 81,0.0
4,dim_pos,name_normalized,text,411,0,411,biopharma plus avenida 249,vitalia farma sur 81,0.0
5,dim_pos,street,text,411,1,94,Calle,Calle 99,0.2
6,dim_pos,door_number,integer,411,1,140,3,150,0.2
7,dim_pos,postal_code,text,411,0,408,10044,UNKNOWN,0.0
8,dim_pos,province,text,411,46,48,A CORUÑA,ZARAGOZA,11.2
9,dim_pos,latitude,numeric,411,46,365,36.012045,43.699820,11.2
10,dim_pos,longitude,numeric,411,46,365,-9.268839,3.202440,11.2
11,dim_pos,is_active,boolean,411,0,2,false,true,0.0
12,dim_pos,match_status,text,411,0,4,GI_ONLY,UNKNOWN,0.0
13,dim_pos,source_system,text,411,0,4,GI,UNKNOWN,0.0
14,dim_pos,match_rule,text,411,211,2,NAME_ADDRESS,NAME_POSTAL_CODE,51.3
15,dim_pos,confidence,numeric,411,211,2,0.8,1.0,51.3

      model                 column             test to
6   dim_pos             confidence  accepted_values
7   dim_pos                 ext_id           unique
8   dim_pos  intervention_point_id           unique
9   dim_pos              is_active         not_null
10  dim_pos             match_rule  accepted_values
11  dim_pos           match_status  accepted_values
12  dim_pos           match_status         not_null
13  dim_pos                   name         not_null
14  dim_pos        name_normalized         not_null
15  dim_pos                pos_key         not_null
16  dim_pos                pos_key           unique
17  dim_pos            postal_code         not_null
18  dim_pos          source_system  accepted_values

### dim_campaign

In [9]:
show_table(MARTS, "dim_campaign")

,campaign_key,campaign_name,campaign_start_date,campaign_end_date,project_id,project_name,client_code
0,1,Campaña Invierno 2025,2025-03-01,2026-12-31,5,Lanzamiento de Producto Parafarmacia,CLI01
1,2,Campaña Primavera 2026,2026-05-27,2026-05-29,9,Gestión de Punto de Venta Consumo,CLI12
2,3,Campaña Otoño 2026,2026-05-31,2026-06-29,1,Lanzamiento de Producto Farma,CLI11
3,4,Campaña Otoño 2026,2026-07-29,2026-07-31,10,Instalación de Expositor Parafarmacia,CLI05
4,5,Campaña Lanzamiento 2026,2026-03-31,2026-04-29,3,Formación de Equipo Parafarmacia,CLI01

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_campaign,campaign_key,integer,17,0,17,-1,16,0.0
1,dim_campaign,campaign_name,text,17,0,10,Campaña Invierno 2025,UNKNOWN,0.0
2,dim_campaign,campaign_start_date,date,17,1,12,2025-03-01,2026-07-29,5.9
3,dim_campaign,campaign_end_date,date,17,1,13,2026-01-03,2026-12-31,5.9
4,dim_campaign,project_id,integer,17,0,12,-1,11,0.0
5,dim_campaign,project_name,text,17,0,12,Auditoría de Lineal Parafarmacia,UNKNOWN,0.0
6,dim_campaign,client_code,text,17,0,8,CLI01,UNKNOWN,0.0

          model        column      test to
0  dim_campaign  campaign_key  not_null
1  dim_campaign  campaign_key    unique
2  dim_campaign   client_code  not_null

### dim_route

In [10]:
show_table(MARTS, "dim_route")

   route_key  campaign_key route_start_date route_end_date route_status
0          1            13       2026-09-08     2026-09-08           OK
1          2            13       2026-09-03     2026-09-03           OK
2          3            13       2026-08-27     2026-08-27           OK
3          4            15       2026-08-24     2026-08-28           OK
4          5            13       2026-08-27     2026-08-28           OK

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_route,route_key,integer,296,0,296,-1,295,0.0
1,dim_route,campaign_key,integer,296,0,17,-1,16,0.0
2,dim_route,route_start_date,date,296,1,106,2025-03-01,2026-09-08,0.3
3,dim_route,route_end_date,date,296,1,109,2025-12-26,2027-01-27,0.3
4,dim_route,route_status,text,296,0,3,GRABADO,UNKNOWN,0.0

        model        column             test                                to
19  dim_route  campaign_key         not_null
20  dim_route  campaign_key    relationships  ref('dim_campaign').campaign_key
21  dim_route     route_key         not_null
22  dim_route     route_key           unique
23  dim_route  route_status  accepted_values
24  dim_route  route_status         not_null

### dim_date

In [11]:
show_table(MARTS, "dim_date")

   date_key    date_day  year  month  week  day_of_week  is_weekend
0  20250301  2025-03-01  2025      3     9            6        True
1  20250302  2025-03-02  2025      3     9            7        True
2  20250303  2025-03-03  2025      3    10            1       False
3  20250304  2025-03-04  2025      3    10            2       False
4  20250305  2025-03-05  2025      3    10            3       False

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_date,date_key,integer,699,0,699,-1,20270127,0.0
1,dim_date,date_day,date,699,1,698,2025-03-01,2027-01-27,0.1
2,dim_date,year,integer,699,1,3,2025,2027,0.1
3,dim_date,month,integer,699,1,12,1,12,0.1
4,dim_date,week,integer,699,1,53,1,53,0.1
5,dim_date,day_of_week,integer,699,1,7,1,7,0.1
6,dim_date,is_weekend,boolean,699,0,2,false,true,0.0

      model      column      test to
3  dim_date    date_key  not_null
4  dim_date    date_key    unique
5  dim_date  is_weekend  not_null

### dim_visit_status

In [12]:
show_table(MARTS, "dim_visit_status")

   status_key visit_status  is_completed  is_incidence
0          -1      UNKNOWN         False         False
1           1           OK          True         False
2           2        INCID          True          True
3           3         INFO         False         False
4           4        NOVIS         False         False

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,dim_visit_status,status_key,integer,5,0,5,-1,4,0.0
1,dim_visit_status,visit_status,text,5,0,5,INCID,UNKNOWN,0.0
2,dim_visit_status,is_completed,boolean,5,0,2,false,true,0.0
3,dim_visit_status,is_incidence,boolean,5,0,2,false,true,0.0

               model        column             test to
25  dim_visit_status  is_completed         not_null
26  dim_visit_status  is_incidence         not_null
27  dim_visit_status    status_key         not_null
28  dim_visit_status    status_key           unique
29  dim_visit_status  visit_status  accepted_values
30  dim_visit_status  visit_status         not_null
31  dim_visit_status  visit_status           unique

### fct_visits

In [13]:
show_table(MARTS, "fct_visits")

,visit_id,pos_key,route_key,campaign_key,status_key,date_key,visit_date,updated_at,is_completed,is_incidence
0,115,025984fb20bc5b7dd2ae86b9ac734b3c,116,10,1,20260102,2026-01-02,2026-02-07,True,False
1,177,b27b0a1a0ca8baed9e22e3a82a2724c9,143,10,1,20260102,2026-01-02,2026-02-07,True,False
2,293,d1a5edecefc8f6751f9d68a26909085e,157,12,2,20260102,2026-01-02,2026-02-07,True,True
3,42,1f62ad40a2716c7a50aa0a3c292a073a,157,12,2,20260102,2026-01-02,2026-02-07,True,True
4,16,0263d00f7588deb121d4623c132c85e9,260,10,1,20260102,2026-01-02,2026-02-07,True,False

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,fct_visits,visit_id,integer,480,0,480,1,480,0.0
1,fct_visits,pos_key,text,480,0,365,00e1fbb665073c505a2f41a05513b7b9,fffbea3800ecb4472fca636dd7025fcd,0.0
2,fct_visits,route_key,integer,480,0,295,1,295,0.0
3,fct_visits,campaign_key,integer,480,0,16,1,16,0.0
4,fct_visits,status_key,integer,480,0,5,-1,4,0.0
5,fct_visits,date_key,integer,480,0,130,20260102,20260908,0.0
6,fct_visits,visit_date,date,480,0,130,2026-01-02,2026-09-08,0.0
7,fct_visits,updated_at,date,480,0,66,2026-01-12,2026-09-08,0.0
8,fct_visits,is_completed,boolean,480,0,2,false,true,0.0
9,fct_visits,is_incidence,boolean,480,0,2,false,true,0.0

,model,column,test,to
39,fct_visits,campaign_key,not_null,
40,fct_visits,campaign_key,relationships,ref('dim_campaign').campaign_key
41,fct_visits,date_key,not_null,
42,fct_visits,date_key,relationships,ref('dim_date').date_key
43,fct_visits,is_completed,not_null,
44,fct_visits,is_incidence,not_null,
45,fct_visits,pos_key,not_null,
46,fct_visits,pos_key,relationships,ref('dim_pos').pos_key
47,fct_visits,route_key,not_null,
48,fct_visits,route_key,relationships,ref('dim_route').route_key
49,fct_visits,status_key,not_null,
50,fct_visits,status_key,relationships,ref('dim_visit_status').status_key
51,fct_visits,updated_at,not_null,
52,fct_visits,visit_id,not_null,
53,fct_visits,visit_id,unique,

In [14]:
check_nulls(MARTS, "fct_visits", ["visit_id", "pos_key", "route_key", "campaign_key", "status_key", "date_key", "updated_at"])

        table        column  nulls status
0  fct_visits      visit_id      0     OK
1  fct_visits       pos_key      0     OK
2  fct_visits     route_key      0     OK
3  fct_visits  campaign_key      0     OK
4  fct_visits    status_key      0     OK
5  fct_visits      date_key      0     OK
6  fct_visits    updated_at      0     OK

In [15]:
run_sql("""
    select count(*) filter (where pos_key = '-1') as pos,
           count(*) filter (where route_key = -1) as route,
           count(*) filter (where campaign_key = -1) as campaign,
           count(*) filter (where status_key = -1) as status,
           count(*) filter (where date_key = -1) as date
    from marts.fct_visits
""")

   pos  route  campaign  status  date
0    0      0         0      14     0

In [16]:
run_sql("""
    select (select count(*) from raw.raw_visits) as raw_rows,
           (select count(*) from staging.stg_visits) as staging_rows,
           (select count(*) from marts.fct_visits) as fact_rows
""")

   raw_rows  staging_rows  fact_rows
0       480           480        480

### fct_campaign_progress

In [17]:
show_table(MARTS, "fct_campaign_progress")

,campaign_key,total_visits_planned,visits_total,visits_completed,visits_incidence,completion_rate
0,1,17,75,71,2,4.1765
1,2,16,15,14,0,0.8750
2,3,5,15,14,0,2.8000
3,4,1,20,20,0,20.0000
4,5,10,22,22,5,2.2000

,table_name,column_name,type,rows,nulls,distinct_values,min,max,null_pct
0,fct_campaign_progress,campaign_key,integer,16,0,16,1,16,0.0
1,fct_campaign_progress,total_visits_planned,integer,16,0,13,1,2000,0.0
2,fct_campaign_progress,visits_total,integer,16,0,12,15,75,0.0
3,fct_campaign_progress,visits_completed,integer,16,0,14,14,71,0.0
4,fct_campaign_progress,visits_incidence,integer,16,0,6,0,9,0.0
5,fct_campaign_progress,completion_rate,numeric,16,0,15,0.0075,54.0000,0.0

,model,column,test,to
32,fct_campaign_progress,campaign_key,not_null,
33,fct_campaign_progress,campaign_key,relationships,ref('dim_campaign').campaign_key
34,fct_campaign_progress,campaign_key,unique,
35,fct_campaign_progress,total_visits_planned,not_null,
36,fct_campaign_progress,visits_completed,not_null,
37,fct_campaign_progress,visits_incidence,not_null,
38,fct_campaign_progress,visits_total,not_null,